# Auto Label PR
# -------------
# This GitHub Actions workflow automatically adds or removes labels on a pull request
# based on a custom Python script that analyzes the PR content and paths.
#
# Steps:
#   - Run pr-auto-label.py to determine which labels to add/remove
#   - Update labels on the PR using GitHub CLI (gh)

name: Auto Label PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflows
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: '.github'

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydantic

      - name: Compute Labels for PR
        id: compute_labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/pr_auto_label.py \
            --repo ${{ github.repository }} \
            --pr ${{ github.event.pull_request.number }}

      - name: Update labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "${{ steps.compute_labels.outputs.remove }}" ]; then
            gh pr edit "${{ github.event.pull_request.number }}" --remove-label "${{ steps.compute_labels.outputs.remove }}"
          fi
          if [ -n "${{ steps.compute_labels.outputs.add }}" ]; then
            gh pr edit "${{ github.event.pull_request.number }}" --add-label "${{ steps.compute_labels.outputs.add }}"
          fi

      - name: Sync Custom Labels from Monorepo PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/pr_fanout_sync_labels.py \
            --repo ${{ github.repository }} \
            --pr "${{ github.event.pull_request.number }}" \
            --config ".github/repos-config.json"
