# Fanout Subtree PRs
# ------------------
# This GitHub Actions workflow detects which subtrees (from a monorepo structure)
# were changed in a pull request, and automatically creates or updates corresponding
# pull requests in their respective original repositories using `git subtree split`.
#
# Steps:
# 1. Checkout the monorepo.
# 2. Set up Python to run detection and fanout scripts.
# 3. Run a Python script to detect which subtrees were changed (based on repos-config.json).
# 4. For each changed subtree, create or update a PR in the corresponding sub-repo.
# 5. (Placeholder) Track or report the child PR status to the monorepo PR.

name: Fanout Subtree PRs

on:
    pull_request:
      types:
        - opened
        - synchronize
        - reopened

jobs:
  fanout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: .github
          sparse-checkout-cone-mode: true
          token: ${{ secrets.MONOREPO_BOT_TOKEN }} # since we are touching subrepository PRs

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydantic requests

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Detect changed subtrees
        id: detect
        env:
          GH_TOKEN: ${{ secrets.MONOREPO_BOT_TOKEN }}
        run: |
          python .github/scripts/pr_detect_changed_subtrees.py \
            --repo "${{ github.repository }}" \
            --pr "${{ github.event.pull_request.number }}" \
            --config ".github/repos-config.json"

      - name: Checkout full repo with changed subtrees
        if: steps.detect.outputs.subtrees
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            .github
            ${{ steps.detect.outputs.subtrees }}
          fetch-depth: 0  # Needed for subtree splitting
          token: ${{ secrets.MONOREPO_BOT_TOKEN }}

      - name: Fan out child PRs
        if: steps.detect.outputs.subtrees
        env:
          GH_TOKEN: ${{ secrets.MONOREPO_BOT_TOKEN }}
        run: |
          python .github/scripts/pr_fanout.py \
            --repo "${{ github.repository }}" \
            --pr "${{ github.event.pull_request.number }}" \
            --subtrees "${{ steps.detect.outputs.subtrees }}"

      - name: Reflect Checks to Monorepo PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/pr_reflect_checks.py \
            --repo ${{ github.repository }} \
            --pr "${{ github.event.pull_request.number }}" \
            --config ".github/repos-config.json"
