name: Synchronize Subtrees

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  MONOREPO_URL: github.com/amd-jmacaran/monorepo-scripts.git
  MONOREPO_BRANCH: main

jobs:
  synchronize-subtrees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Monorepo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # needed for git subtree pull/push
          token: ${{ secrets.MONOREPO_BOT_TOKEN }}

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Repositories in the Monorepo
        run: |
          has_errors=false
          for repo in $(cat .github/repos-config.json | jq -r '.repositories[].name'); do
            repo_name=$(cat .github/repos-config.json | jq -r ".repositories[] | select(.name == \"$repo\") | .reponame")
            url=$(cat .github/repos-config.json | jq -r ".repositories[] | select(.name == \"$repo\") | .url")
            branch=$(cat .github/repos-config.json | jq -r ".repositories[] | select(.name == \"$repo\") | .branch")
            category=$(cat .github/repos-config.json | jq -r ".repositories[] | select(.name == \"$repo\") | .category")

            git subtree pull --prefix "${category}/${repo}" https://github.com/${url}.git $branch || {
              has_errors=true
            }

            # Uncomment to enable pushing back to remote
            # git subtree push --prefix "${category}/${repo}" https://github.com/${url}.git $branch || {
            #   has_errors=true
            # }
          done

          if [ "$has_errors" = true ]; then
            echo "One or more errors occurred during the repository update."
            exit 1
          else
            git push https://${{ env.MONOREPO_URL }} ${{ env.MONOREPO_BRANCH }}
            echo "All repositories updated successfully!"
          fi
